name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run 
        run: |
           docker compose up -d
           sleep 10

      - name: Run frontend
        run: |
          npm install --force
          nohup npm start &
        working-directory: ./frontend

      - name: Build and push images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |-
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          cd backend
          docker build -t $DOCKERHUB_USERNAME/backend:latest .
          docker push $DOCKERHUB_USERNAME/backend:latest
          cd ../frontend
          docker build -t $DOCKERHUB_USERNAME/frontend:latest .
          docker push $DOCKERHUB_USERNAME/frontend:latest
          
