name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Construir imágenes Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend

      - name: Iniciar sesión en DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Subir imágenes a DockerHub
        run: |
          cd backend
          docker build -t  ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .
          docker push  ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          cd ../frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Cerrar sesión en DockerHub
        run: docker logout
        if: always()