name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "prueba" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install --force  # Asegura que las dependencias del backend estén instaladas

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install --force  # Asegura que las dependencias del frontend estén instaladas

      - name: Build and run 
        run: |
          docker compose up -d
          sleep 10

      - name: Run frontend
        run: |
          cd frontend
          nohup npm start &
        working-directory: ./frontend

      - name: Build and push images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |-
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          cd backend
          docker build -t $DOCKERHUB_USERNAME/backend:latest .
          docker push $DOCKERHUB_USERNAME/backend:latest
          cd ../frontend
          docker build -t $DOCKERHUB_USERNAME/frontend:latest .
          docker push $DOCKERHUB_USERNAME/frontend:latest
          
